# Generated by Django 5.2.8 on 2025-11-05 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_adicional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 5, 20, 30, 23, 877437, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
