# Generated by Django 5.2.8 on 2025-11-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_adicional', '0002_reservaservicio_fecha_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaservicio',
            name='fecha_reserva',
        ),
    ]
