# Generated by Django 5.2.8 on 2025-11-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicio_adicional", "0002_reservaservicio_fecha_reserva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservaservicio",
            name="fecha_reserva",
            field=models.DateTimeField(),
        ),
    ]
