# Generated by Django 5.2.7 on 2025-11-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_adicional', '0003_alter_reservaservicio_fecha_reserva'),
        ('servicio_adicional', '0003_remove_reservaservicio_fecha_reserva'),
    ]

    operations = [
    ]
