# Generated by Django 5.2.8 on 2025-11-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="comprobante",
            field=models.FileField(blank=True, null=True, upload_to="comprobantes/"),
        ),
    ]
